spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: 12345
  jpa:
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate.ddl-auto: create
server:
  port: 8088
usercontroller:
  messages:
    exception1: User Not Found
    exception2: Sucessfully Created
    exception3: please fill in username and password
    exception4: user email not found
    exception5: Invalid Login.Please check your email and password
jwtfilter:
  messages:
    exception1: Missing or invalid Authorization header
    exception2: Invalid token
kafka:
  ipAddress: 172.23.239.245:9092
  groupId: group_id54
  listeningTopic: user
  containerFactory: kafkaUserListenerContainerFactory