  image: docker:latest
  services:
  - docker:dind

  variables:
    DOCKER_DRIVER: overlay
    SPRING_PROFILES_ACTIVE: gitlab-ci

  stages:
  - build
  - test
  - code_quality

  maven-build:
    image: maven:3-jdk-10
    stage: build
    script: "mvn clean test"
    artifacts:
      paths:
      - "*/target/*.jar"

  test:
      script: 
      - cat /config-server/target/jacoco-ut/index.html

  code_quality:
      stage: code_quality
      image: docker:stable
      variables:
          DOCKER_DRIVER: overlay2
      allow_failure: true
      script: "mvn package"
      artifacts:
          paths: [gl-code-quality-report.json]




  #  docker-build:
#    stage: package
#    script:
#    - docker build -t registry.gitlab.com/marcolenzo/actuator-sample .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/marcolenzo/actuator-sample