  image: docker:latest
  services:
  - docker:dind

  variables:
    DOCKER_DRIVER: overlay
    SPRING_PROFILES_ACTIVE: gitlab-ci

  stages:
  - build
  - test
  - package

  maven-build:
    image: maven:3-jdk-10
    script: "mvn package"
    artifacts:
      paths:
      - /target/*.jar

  test:
      image: maven:3-jdk-10
      script:
      - mvn test

  code_quality:
    image: docker:stable
    variables:
      DOCKER_DRIVER: overlay2
    allow_failure: true
    services:
    - docker:stable-dind
    script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
    artifacts:
      paths: [gl-code-quality-report.json]


  #  docker-build:
#    stage: package
#    script:
#    - docker build -t registry.gitlab.com/marcolenzo/actuator-sample .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/marcolenzo/actuator-sample