  image: docker:latest
  services:
  - docker:dind

  variables:
    DOCKER_DRIVER: overlay
    SPRING_PROFILES_ACTIVE: gitlab-ci

  stages:
  - build
  - test
  - package
  - deploy
  maven-build:
    image: maven:3-jdk-10
    stage: build
    script: "mvn clean test"
    artifacts:
      paths:
      - target/*.jar

#  test:
#      stage: test
#      script: "mvn clean test"
#      artifacts:
#        paths:
#            -target/jacoco-ut/*.html
  pages:
      stage: deploy
      dependencies:
      - maven-build
      script:
      - mkdir public
      - mv target/jacoco-ut/*.html public
      artifacts:
          paths:
          - public
      only:
      - master

  #  docker-build:
#    stage: package
#    script:
#    - docker build -t registry.gitlab.com/marcolenzo/actuator-sample .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker push registry.gitlab.com/marcolenzo/actuator-sample