version:  '2.0'
services:
  # eureka:
  #   image: eureka:v1
  #   build: eureka-registry/
  #   restart: always
  #   container_name: eureka-container
  #   network_mode: host
  #   ports:
  #     - 8091:8091 

  #   expose:
  #     - 8091

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.23.239.245
      KAFKA_CREATE_TOPICS: "education:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.23.239.245:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  # config-server:
  #   image: config-server:v1
  #   build: config-server/
  #   restart: always
  #   container_name: config-container
  #   network_mode: host
  #   depends_on:
  #     - eureka
  #   ports:
  #     - 8092:8092
  #   expose:
  #     - 8092

  # mongodb:
  #   image: mongo:3.2-jessie
  #   ports:
  #     - "27017:27017"
  #   container_name: mongo-movie
  #   network_mode: host
  #   depends_on:
  #     - config-server
  #   volumes:
  #     - '/home/cgi/data/mysql:/data/db'

#  movie-demo:
#    image: movie-mongo:v1
#    build: movie-cruiser-app/
#    restart: always
#    container_name: mongo-demo-compose
#    network_mode: host
#    depends_on:
#      - mongodb
#    ports:
#      - 8090:8090
#    expose:
#      - 8090

  # gateway:
  #   image: zuulgateway:v1
  #   build: zuulgateway/
  #   restart: always
  #   container_name: zuul-container
  #   network_mode: host
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 8081:8081
  #   expose:
  #     - 8081
