server:
  port: 8084

management:
  security:
    enabled: false

eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application.name: LocationService
  cloud.config.uri: http://localhost:8888

kafka:
  ipAddress: 172.23.239.245:9092
  groupId: group_id11
  outputTopic: indexer
  listeningTopic: location
  containerFactory: userKafkaListenerFactory