server:
  port: 8085

spring:
  application:
    name: CertificationService
  cloud:
    config:
      uri: http://localhost:8888

kafka:
  ipAddress: 172.23.239.245:9092
  groupId: group_id3
  outputTopic: indexer
  listeningTopic: certificate
  containerFactory: userKafkaListenerFactory