server:
  port: 8083
spring:
  application.name: ProjectService
  cloud.config.uri: http://localhost:8888
kafka:
  ipAddress: localhost:9092
  groupId: group_id45
  outputTopic: indexer
  listeningTopic: project
  containerFactory: userKafkaListenerFactory